### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by drvinceknight** [Moduleplanner/Moduleplanner.github.io#21]
Is it worth putting some documentation together (hosted with read the docs perhaps) just for instructions as to how to put the database together?

**Comment by AdamPohl** [comment]
I will start doing this on thursday :imp:

**Comment by drvinceknight** [comment]
This would be my suggestion: http://docs.readthedocs.org/en/latest/getting_started.html

**Comment by AdamPohl** [comment]
@geraintpalmer as you have set up the docs for us, could you make a pr please so that I can start filling in bits of the english version. thanks :imp:

Done with #62 I can now start filling in things
