### ISSUE TITLE
Name of repo

### ISSUE THREAD

**Issue by drvinceknight** [Moduleplanner/Moduleplanner.github.io#22]
Would it be better for this to have Cardiff and Math somewhere in the title?

Just thinking that this can be easily used by other schools/universities etc... and perhaps the easiest way to deal with this would be to simply clone this repo and change the db (see #21).

You guys might have already thought about this. Just a suggestion.

**Comment by drvinceknight** [comment]
Maybe it's nicer to have this clean url as the first one and people can just clone and add a crappy long name...

**Comment by AdamPohl** [comment]
The end plan of mine is to have it all in one repo, with different folders in the _data folder but that might be a lot more complicated than this idea, me and Alex will have to discuss this

**Comment by drvinceknight** [comment]
I'm not sure that's very scalable, ideally you don't want a centralised tool but something that anyone can use/change etc... Any school/university etc can clone and be up and running.

**Comment by drvinceknight** [comment]
I'm closing this as I think it's nice for the original one (yours) to keep it's name.
