### ISSUE TITLE
Selecting modules

### ISSUE THREAD

**Issue by PepperSwan** [Moduleplanner/Moduleplanner.github.io#25]
The modules for which a "Requires: " field opens do not turn red when selected; nor does the "Requires: " field retract after being clicked again

Other than that I think it's bloody brilliant

**Comment by AdamPohl** [comment]
@PepperSwan Which modules are you finding this with, I thought I had gone through most of the options manually and they worked for me.

**Comment by PepperSwan** [comment]
@Huaraz2 on BSc Mathematics:
Elementary Number Theory II
Elementary Fluid Dynamics
Mechanics II
Foundations of Probability and Statistics 
Programming and Statistics

I'm using it on my laptop with Google Chrome

**Comment by AdamPohl** [comment]
@PepperSwan Ignore my last comment, I miss understood what you were saying, the fact that the modules with requirements don't turn red when selected (if written correctly) iff their requirements are unselected. At the moment the requirements field only closes if the pre-requests are selected, we may look at the option to minimize this without selecting the module for a future realese. Thanks for the feedback, hope this clarifies your issue.

> Other than that I think it is bloody brilliant

I am glad you like it :+1: :smiling_imp:

**Comment by PepperSwan** [comment]
OH WOW

**Comment by PepperSwan** [comment]
Now I understand

**Comment by drvinceknight** [comment]
Could anything have been presented differently @PepperSwan so that that was
clear?

**Comment by PepperSwan** [comment]
Perhaps an introduction into selecting first year modules before moving onto second,

Although in reality this was probably just me being a dumb.

**Comment by drvinceknight** [comment]
I'm not sure that's a good idea as this tool could also be used by
selecting final year things first to help figure out what to pick in first
and second... What do you think?

**Comment by AdamPohl** [comment]
@PepperSwan The overarching idea me and Alex had was that you could select a module that you really wanted to do in say 3rd yr and then be able to see what modules you had to take to take it and therefore help you to better plan out your degree

**Comment by PepperSwan** [comment]
To be honest it's incredibly useful even now as I wasn't entirely sure what modules were available, or which lead on to which...

I think the way it is laid out is fine, because you can look through the third year modules, and if you click on them it tells you which modules you require.

I'm actually using it right now to help plan

**Comment by PepperSwan** [comment]
For some modules, such as Programming and Statistics, you require an optional module from the same year..  Perhaps laying out the modules into their respective terms could make things simpler.

**Comment by PepperSwan** [comment]
Also, just playing around with it,

To take Multivariate Statistics you must take Foundations of Probability and Statistics,
And to take Foundations of Probability and Statistics you must take Statistical Inference

Now if all three are selected and I UNSELECT Statistical Inference,
Foundations of Probability and Statistics automatically unchecks itself but Multivariate Statistics stays selected

Very very minor problem, but hey

**Comment by AdamPohl** [comment]
@PepperSwan Interesting bug, will look into this.

**Comment by alcarney** [comment]
@Huaraz2 so.. is this fixed now??

**Comment by AdamPohl** [comment]
@alcarney The bug that was picked up near the end of this chat is fixed, was going to leave it open till we had a chance to talk about the other issue raised here, ie re clicking a module closes its requirements without selecting the module if they are not chosen.
