### ISSUE TITLE
Gitter, slack, telegram room?

### ISSUE THREAD

**Issue by drvinceknight** [Moduleplanner/Moduleplanner.github.io#26]

**Comment by AdamPohl** [comment]
we have a telegram room fo module planner it h=only has me and Alex in and I have linked this repo to it, do you want to join?

**Comment by drvinceknight** [comment]
Why not :) A more open facing thing could be useful for people to jump in
to report bugs perhaps?

**Comment by AdamPohl** [comment]
I have created a group chat on facebook for the people I asked to test it (most of the people who do maths here that I have as freinds) and said to post issues they find in there or to create an issue on github about it. I did kind of hijack your 1st yr module gitter chat (sorry) to let the first yrs know but I did ask them to make an issue on the repo about bugs / problems they inccured.

**Comment by AdamPohl** [comment]
WIll close due to #61
