### ISSUE TITLE
Local storage

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#27]
We should look at adding local storage to the site for the next round of testing (something like what you did for the code club site @alcarney) preferably I think it should remember the module choses you hsve made and open into the degree scheme you have selected them for

**Comment by AdamPohl** [comment]
when you get a chance could you look into this next @alcarney please. :imp:

**Comment by alcarney** [comment]
Will do, can do it while adding the js tests :metal:

**Comment by AdamPohl** [comment]
@alcarney Cool Cool :imp:
