### ISSUE TITLE
Degree schemes are not centered

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#3]
As you can see in the pic below, the degree schemes appear next to the 'title' rather than below the modules do with the year.

![image](https://cloud.githubusercontent.com/assets/8998661/13444108/4bc614b6-dffc-11e5-8a06-fcd3132706f1.png)

**Comment by alcarney** [comment]
This is because in the html everything is wrapped in a div with class `planner` this causes it to inherit the flexbox rules and tries to put all of its immediate children into separate columns.

A fix would either be to change the class to something else or wrap the heading and the `core` div in another div

**Comment by AdamPohl** [comment]
I have changed the divs and the screen now looks like this:
![image](https://cloud.githubusercontent.com/assets/8998661/13460469/a739120a-e072-11e5-9745-295e24781977.png)

Is there any way to have all of it in the center column of the screen?

**Comment by alcarney** [comment]
In the html for that page give the body tag an id say "courses"

Then in the css.

```
body#courses > div.planner {
    justify-content: center;
}
```

Make sure this is after the other `div.planner` rules

**Comment by AdamPohl** [comment]
This is the current state of the code in index.html:
![image](https://cloud.githubusercontent.com/assets/8998661/13460634/b9cb33fc-e073-11e5-8193-8c41ade11012.png)

What do you want me to do in the CSS?

**Comment by AdamPohl** [comment]
And this is what I have put in the css to get the output above:

![image](https://cloud.githubusercontent.com/assets/8998661/13460675/08579718-e074-11e5-82eb-71a3e2218a2d.png)

**Comment by alcarney** [comment]
I meant to give the body tag an id ie

`<body id="courses">`

I gave the css code above

**Comment by alcarney** [comment]
Sorry I missed read the html

**Comment by AdamPohl** [comment]
My last two screenshots are just to show you what I did to make the output you see below (this is the same as the one I sent earlier):
![image](https://cloud.githubusercontent.com/assets/8998661/13460715/743961f0-e074-11e5-840a-3a294440441e.png)

**Comment by AdamPohl** [comment]
What do you think of this?

![image](https://cloud.githubusercontent.com/assets/8998661/13497697/a1d269c4-e14e-11e5-8990-076eccdbbdbd.png)

**Comment by AdamPohl** [comment]
ignore the word test that is above it, I am trying to add a degree title in for the module selector part

**Comment by alcarney** [comment]
Looks good

**Comment by AdamPohl** [comment]
:+1:  will close this now then
