### ISSUE TITLE
english cyfieithu Cymraeg

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#39]
@geraintpalmer mae angen i ni gyfieithu holl ddata o'r Saesneg i'r Gymraeg.  Diolch am gytuno i wneud hyn.  :imp:  :+1: :metal:

**Comment by geraintpalmer** [comment]
Dim problem! :hatching_chick:

**Comment by AdamPohl** [comment]
@geraintpalmer could you please add a comment here with the welsh translation to the following words please:
    - Year
    - Clear Selected
    - Credits
    - Requires
    - More info
    - Please choose your degree scheme
    - School of Mathematics
    - Credits chosen

Thanks :imp: :+1:

**Comment by geraintpalmer** [comment]
- Blwyddyn
- Clirio dewisiadau (clear selections)
- Credydau
- Angen (needs) ('modiwlau ofynnol' is better, means 'required modules'
- Mwy o wybodaeth
- Dewiswch eich cynllun gradd os gwelwch yn dda
- Yr Ysgol Fathemateg
- Credydau a ddewiswyd

**Comment by AdamPohl** [comment]
@geraintpalmer Thanks :+1:

**Comment by AdamPohl** [comment]
@geraintpalmer Could I also have the welsh translation for:
- Change your degree

please :+1: :imp: :dragon:

**Comment by geraintpalmer** [comment]
Newidwch eich cynllun gradd (change your degree scheme) 🐣

**Comment by AdamPohl** [comment]
@geraintpalmer Diolch :+1:
