### ISSUE TITLE
Add a landing page?

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#40]
I feel like we should have the logo and name of the school somewhere in the site (this has also been mentioned in some of the feedback i have recieved) so I thought of using a landing page like we have for the code club site (see pic below). What do you think?

![image](https://cloud.githubusercontent.com/assets/8998661/13699536/e9285908-e772-11e5-9ec6-aecb6653f927.png)

**Comment by alcarney** [comment]
@Huaraz2 I felt from the discussion in code club yesterday we should keep the module planner generic without any particular branding...

Unless you mean we add a landing page that's easily customisable to fit a particular school/uni?

**Comment by AdamPohl** [comment]
@alcarney That was the plan, ie have the uni logo instead of the code club one and have the name of the school and then a button to go to the page to select your degree
