### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#49]
Do we add a disclaimer to the bottem of the index page saying that not all of the modules on here may not exist when they get to that year? ie Vince's 3rd yr module MA3600 is there but it will not be avalible next year as far as I am aware as it is splitting into two 10 credit modules: Queueing & Inventory theory and Game Theory.

**Comment by AdamPohl** [comment]
@alcarney @drvinceknight what do you think about this?

**Comment by alcarney** [comment]
Might be a good idea, at least until the data is verified :)

**Comment by AdamPohl** [comment]
@alcarney Ok cool will look at this later

**Comment by drvinceknight** [comment]
No matter what: until this is completely run by the university (which it may or may not be, some sort of wiki model could be cool...) it needs a disclaimer. This is important. You don't want responsibility, it has to make it clear that this is a service offered with an aim to be helpful but that all choices and prerequisites should be checked against the official university website (and to invite people to let you know if there's an error).

:+1:
