### ISSUE TITLE
modules can't be selected even if their pre-requsits are

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#5]
jekyll builds fine but it won't let me select modules that have pre requisits, see gif below.

![issue](https://cloud.githubusercontent.com/assets/8998661/13459427/64d8835c-e06b-11e5-97cb-e18ca7fd6602.gif)

**Comment by alcarney** [comment]
You moved the p tag into the requires div when you should have just given it the class requires i.e 

`<p class="requires">Requires</p>`

**Comment by AdamPohl** [comment]
:+1: thanks @alcarney it is sorted now.
