### ISSUE TITLE
language won't change from english

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#58]
english selected:
![image](https://cloud.githubusercontent.com/assets/8998661/13990065/cc896a8e-f10a-11e5-9029-707d40ab53fb.png)

Welsh selected:
![image](https://cloud.githubusercontent.com/assets/8998661/13990071/d60e01fa-f10a-11e5-8f39-cdd9660b9cef.png)

**Comment by alcarney** [comment]
Odd. Works fine locally, does it work locally for you?

**Comment by AdamPohl** [comment]
@alcarney no it does not

**Comment by AdamPohl** [comment]
as it is a local storage issue I am going to close this now
