### ISSUE TITLE
Add a dark & light/material theme

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#6]
We should have a dark and a light theme ready for the beta1 launch as not everyone likes looking at a dark screen

**Comment by AdamPohl** [comment]
@alcarney all we really need is one decent theme (a version of the Cardiff red theme) before we release beta1

**Comment by AdamPohl** [comment]
@alcarney I think it would be best if we start with a dark(no change) and light version of Cardif Red for beta2 testing and when we do it I will stress the style of the page as I have the mobile site design/layout

**Comment by AdamPohl** [comment]
This is not currently going well

**Comment by AdamPohl** [comment]
At least jekyll runs though (now)

**Comment by AdamPohl** [comment]
see https://github.com/Huaraz2/Moduleplanner.github.io/tree/Themes for where I am at the moment

**Comment by alcarney** [comment]
Now done via #30
