### ISSUE TITLE
Stuff to do tomorrow before PyDiff

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#63]
- [x] Finish Documentation
- [x] Create settings.yml file
- [x] Add disclaimeer
- [x] Make presentation
- [x] Breath (it is almost over)
- [x] Look at Flask api (no python in talk otherwise)
- [x] If Flask turns out to be the devil nock up a django version
- [ ] Run through presentation at least once to get timings right
- [x] Breath (again)
- [x] Take nessarcy pics
- [x] Rock the lightning talk

**Comment by drvinceknight** [comment]
This looks great! Don't worry too much if there's no Python, this is a lightning talk so it can be about anything :)

> Rock the lightning talk

🎸  :shipit:

**Comment by AdamPohl** [comment]
@drvinceknight Ok thanks
