### ISSUE TITLE
Consider renaming some things

### ISSUE THREAD

**Issue by alcarney** [Moduleplanner/Moduleplanner.github.io#76]
It might be a good idea to go through the codebase and rename a few variables so they are more intuitive and user friendly - especially before we "release" this. For example consider what is needed to add a new course:

```
layout: course
short: bsc
lang: cy
```

`layout` and `lang` I think are fine, but what about `short`? What's short? It was fine during development as we knew what we were talking about, but a new user won't know what we mean by short, it might be better to call it something like `degreecode`. That way just by looking it's more obvious what the user should put there and they don't necessarily have to digging through the docs to find out what they should be writing.

**Comment by AdamPohl** [comment]
@alcarney do you think the docs are not that easy to read?

**Comment by alcarney** [comment]
That's not what I'm saying at all. Just that we should consider renaming a few things so that it's more obvious what they are for, just from the name alone. Take `short` again for example, we use short to refer to both a language code and a degree code. By renaming them to something more descriptive it should speed up the process of new people coming in and familiarising themselves with the systems in place.

**Comment by drvinceknight** [comment]
:+1: @alcarney 

Remember, no points for short variable names.

**Comment by AdamPohl** [comment]
We can look at this tomorrow in our meeting @alcarney
