### ISSUE TITLE
fixing more-info links

### ISSUE THREAD

**Issue by AdamPohl** [Moduleplanner/Moduleplanner.github.io#8]
This is the code I have wriiten:
![image](https://cloud.githubusercontent.com/assets/8998661/13460004/a6a9a1f4-e06f-11e5-8b19-51f1bb908053.png)

And they are coming out like this:
![image](https://cloud.githubusercontent.com/assets/8998661/13460029/d288e19a-e06f-11e5-9d9c-1e1ab9ae5c55.png)

But when I click on the link I get this screen:
![image](https://cloud.githubusercontent.com/assets/8998661/13460014/b5935ebc-e06f-11e5-950d-b22e0d3b799e.png)

Any Ideas?

**Comment by alcarney** [comment]
So in other words code.more-info doesn't exist

Also that link should go in the _includes/module_info.html file

**Comment by AdamPohl** [comment]
It now works but it has shown me a problem, some of the modules I got of the website no longer exist
